# Per-commit
trigger:
  - master
# All PRs
pr:
  branches:
    include:
    - '*'

pool:
  name: Default
  demands: CUSTOM_CAPABILITY -equals ompi

variables:
  ompi_ci_docker_registry_url: rdmz-harbor.rdmz.labs.mlnx
  ompi_ci_docker_registry_repo: hpcx
  ompi_ci_docker_image_name: ompi_ci
  ompi_ci_docker_image_tag: latest
  # TODO: change to the main repo and master branch
  #ompi_jenkins_scripts_git_repo_url: https://github.com/mellanox-hpc/jenkins_scripts.git
  ompi_jenkins_scripts_git_repo_url: https://github.com/itemko/jenkins_scripts.git
  #ompi_jenkins_scripts_git_branch: master
  ompi_jenkins_scripts_git_branch: artemry/ompi_review
  # Enable debug information, supported values: true, false
  debug: true

jobs:
- job: mellanox_ompi_ci
  displayName: Mellanox OpenMPI CI
  timeoutInMinutes: 240
  container:
    image: $(ompi_ci_docker_registry_url)/$(ompi_ci_docker_registry_repo)/$(ompi_ci_docker_image_name):$(ompi_ci_docker_image_tag)
    options: -v /hpc/local:/hpc/local -v /opt:/opt --network=host --uts=host --ipc=host --ulimit stack=67108864
      --ulimit memlock=-1 --security-opt seccomp=unconfined --cap-add=SYS_ADMIN --device=/dev/infiniband/ --user swx-jenkins
  steps:
  - task: DeleteFiles@1
    displayName: Cleanup workspace folder
    inputs:
      sourceFolder: $(Pipeline.Workspace)
      contents: |
        **/*
  - checkout: self
    submodules: true
    path: ompi
  - bash: |
      set -eE
      [ "$(debug)" = "true" ] && set -x
      git clone $(ompi_jenkins_scripts_git_repo_url)
      cd jenkins_scripts && git checkout $(ompi_jenkins_scripts_git_branch) && cd - > /dev/null
      export WORKSPACE=$(Build.SourcesDirectory)/ompi
      # TODO: rework ompi_test.sh to avoid Jenkins mentions
      export JENKINS_RUN_TESTS=yes
      $(Build.SourcesDirectory)/jenkins_scripts/jenkins/ompi/ompi_test.sh
    displayName: Build and test OpenMPI
