# https://aka.ms/yaml

trigger:
  - master
pr:
  - master

pool:
  vmImage: 'ubuntu-16.04'

# container: ucfconsort.azurecr.io/ucx/centos7::latest

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - bash: |
      set -eE
      printenv
      cat /proc/1/cgroup
      cat /etc/*release*
      pwd
      df -kh .
      ls -al
