# https://aka.ms/yaml

trigger:
  - master
pr:
  - master

pool:
  vmImage: 'ubuntu-16.04'

container: centos:7

resources:
  repositories:
    - repository: jenkins_scripts
      type: github
      endpoint: itemko
      name: itemko/jenkins_scripts
      ref: artemry/ompi_review

steps:
  - checkout: self
    submodules: true
  - checkout: jenkins_scripts
  - bash: |
      set -eE
      echo "==============================================================================="
      hostname
      echo "==============================================================================="
      printenv
      echo "==============================================================================="
      cat /proc/1/cgroup
      echo "==============================================================================="
      cat /etc/*release*
      echo "==============================================================================="
      pwd
      echo "==============================================================================="
      df -kh .
      echo "==============================================================================="
      ls -al
      echo "==============================================================================="
      id
      echo "==============================================================================="
