# https://aka.ms/yaml

trigger:
  - master
# TODO all the PRs
pr:
  - master

pool:
  #vmImage: 'ubuntu-16.04'
  name: Default
  demands: CUSTOM_CAPABILITY -equals qqq

#container: centos:7

#resources:
#  repositories:
#    - repository: jenkins_scripts
#      type: github
#      endpoint: itemko
#      name: itemko/jenkins_scripts
#      ref: artemry/ompi_review

variables:
  docker_build_context_dir: /tmp/ompi_build_docker_image_$(BUILD_BUILDID)
  var1: $(BUILD_BUILDID)
  var2: $(build_buildid)
  var3: ${BUILD_BUILDID}
  var4: $[ variables['BUILD_BUILDID'] ]

steps:
  - checkout: self
    submodules: true
    path: ompi
  - bash: |
      echo "INFO: VAR1 = $VAR1"
      echo "INFO: VAR2 = $VAR2"
      echo "INFO: VAR3 = $VAR3"
      echo "INFO: VAR4 = $VAR4"
      echo "INFO: DOCKER_BUILD_CONTEXT_DIR = ${DOCKER_BUILD_CONTEXT_DIR}"
      rm -rf ${DOCKER_BUILD_CONTEXT_DIR}
      mkdir -p ${DOCKER_BUILD_CONTEXT_DIR}
  - task: Docker@2
    displayName: Build docker image
    inputs:
      command: build
      Dockerfile: Dockerfile
      arguments: --no-cache --network=host --rm --force-rm --label=ompi --build-arg OMPI_CI_OS=${OMPI_CI_OS} --build-arg OMPI_CI_OFED=${OMPI_CI_OFED}
      buildContext: $(docker_build_context_dir)
#  - checkout: jenkins_scripts
  - bash: |
      echo "==============================================================================="
      hostname
      echo "==============================================================================="
      printenv
      echo "==============================================================================="
      cat /proc/1/cgroup
      echo "==============================================================================="
      cat /etc/*release*
      echo "==============================================================================="
      pwd
      echo "==============================================================================="
      df -kh .
      echo "==============================================================================="
      ls -al
      echo "==============================================================================="
      id
      echo "==============================================================================="
  - bash: |
      set -x
      git clone https://github.com/itemko/jenkins_scripts.git
      cd jenkins_scripts && git checkout artemry/ompi_review && cd - > /dev/null
      export WORKSPACE=${BUILD_SOURCESDIRECTORY}/ompi
      ${BUILD_SOURCESDIRECTORY}/jenkins_scripts/jenkins/ompi/ompi_jenkins.sh
