# https://aka.ms/yaml

trigger:
  - master
pr:
  - master

pool:
  vmImage: 'ubuntu-16.04'

container:
  image: docker.io/centos7:latest
  endpoint: itemko_private_dockerhub

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - bash: |
      set -eE
      echo "==============================================================================="
      hostname
      echo "==============================================================================="
      printenv
      echo "==============================================================================="
      cat /proc/1/cgroup
      echo "==============================================================================="
      cat /etc/*release*
      echo "==============================================================================="
      pwd
      echo "==============================================================================="
      df -kh .
      echo "==============================================================================="
      ls -al
      echo "==============================================================================="
      id
      echo "==============================================================================="
      docker images
      echo "==============================================================================="
      docker ps -a
      echo "==============================================================================="
