# https://aka.ms/yaml

trigger:
  - master
# TODO all the PRs
pr:
  - master

pool:
  name: Default
  demands: CUSTOM_CAPABILITY -equals ompi

steps:
  - checkout: self
    submodules: true
    path: ompi
  - bash: |
      echo "==============================================================================="
      hostname
      echo "==============================================================================="
      printenv
      echo "==============================================================================="
      cat /proc/1/cgroup
      echo "==============================================================================="
      cat /etc/*release*
      echo "==============================================================================="
      pwd
      echo "==============================================================================="
      df -kh .
      echo "==============================================================================="
      ls -al
      echo "==============================================================================="
      id
      echo "==============================================================================="
      docker images
      echo "==============================================================================="
      docker ps -a
      echo "==============================================================================="
  - bash: |
      set -x
      hostname
      cat /proc/1/cgroup
      git clone https://github.com/itemko/jenkins_scripts.git
      cd jenkins_scripts && git checkout artemry/ompi && cd - > /dev/null
      export WORKSPACE_JENKINS_SCRIPTS=${BUILD_SOURCESDIRECTORY}/jenkins_scripts
      export WORKSPACE_OMPI=${BUILD_SOURCESDIRECTORY}/ompi
      ${WORKSPACE_JENKINS_SCRIPTS}/jenkins/ompi/ompi_jenkins_docker_launcher.sh
