# https://aka.ms/yaml

trigger:
  - master
# TODO all the PRs
pr:
  - master

pool:
  name: Default
  demands: CUSTOM_CAPABILITY -equals ompi

variables:
  ompi_ci_os_name: centos
  ompi_ci_os_version: 7
  ompi_ci_ofed: mofed-4.7-1.0.0.1
  ompi_jenkins_scripts_git_repo_url: https://github.com/itemko/jenkins_scripts.git
  ompi_jenkins_scripts_git_branch: artemry/ompi_review
  debug: true

steps:
- checkout: self
  submodules: true
  path: ompi
- bash: |
    set -eEx
    DOCKER_BUILD_CONTEXT_DIR="/tmp/ompi_build_docker_image_${BUILD_BUILDID}"
    rm -rf ${DOCKER_BUILD_CONTEXT_DIR}
    mkdir -p ${DOCKER_BUILD_CONTEXT_DIR}
    echo "##vso[task.setvariable variable=docker_build_context_dir]${DOCKER_BUILD_CONTEXT_DIR}"
- bash: |
    echo "INFO: DOCKER_BUILD_CONTEXT_DIR = ${DOCKER_BUILD_CONTEXT_DIR}"
- task: Docker@2
  displayName: Build docker image
  inputs:
    command: build
    Dockerfile: Dockerfile
    arguments: --no-cache --network=host --rm --force-rm --label=ompi --build-arg OMPI_CI_OS=$(ompi_ci_os_name):$(ompi_ci_os_version) --build-arg OMPI_CI_OFED=$(ompi_ci_ofed)
    buildContext: $(DOCKER_BUILD_CONTEXT_DIR)
    repository: $(OMPI_CI_OS_NAME)_ompi
    tags: $(Build.BuildId)
- bash: |
    echo "==============================================================================="
    hostname
    echo "==============================================================================="
    printenv
    echo "==============================================================================="
    cat /proc/1/cgroup
    echo "==============================================================================="
    cat /etc/*release*
    echo "==============================================================================="
    pwd
    echo "==============================================================================="
    df -kh .
    echo "==============================================================================="
    ls -al
    echo "==============================================================================="
    id
    echo "==============================================================================="
    docker images
    echo "==============================================================================="
    docker ps -a
    echo "==============================================================================="
- bash: |
    set -eEx
    git clone $(ompi_jenkins_scripts_git_repo_url)
    cd jenkins_scripts && git checkout $(ompi_jenkins_scripts_git_branch) && cd - > /dev/null
    export WORKSPACE_JENKINS_SCRIPTS=$(BUILD_SOURCESDIRECTORY)/jenkins_scripts
    export WORKSPACE_OMPI=$(BUILD_SOURCESDIRECTORY)/ompi
    export OMPI_CI_DOCKER_IMAGE_NAME=$(OMPI_CI_OS_NAME)_ompi:$(Build.BuildId)
    $(WORKSPACE_JENKINS_SCRIPTS)/jenkins/ompi/ompi_jenkins_docker_launcher.sh
#- bash: |
#    docker images
#    docker ps -a
#    docker rmi $(OMPI_CI_OS_NAME)_ompi:$(Build.BuildId)
#    docker images
#    docker ps -a
