# https://aka.ms/yaml

trigger:
  - master
pr:
  - master

pool:
  vmImage: 'ubuntu-16.04'

container: centos7

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
    printenv
    cat /proc/1/cgroup
    cat /etc/*release*
    pwd
    df -kh .
    ls -al
