# https://aka.ms/yaml

trigger:
  - master
# TODO all the PRs
pr:
  - master

pool:
  name: Default
  demands: CUSTOM_CAPABILITY -equals ompi

container: centos:7

steps:
  - checkout: self
      submodules: true
      path: ompi
  - bash: |
      echo "==============================================================================="
      hostname
      echo "==============================================================================="
      printenv
      echo "==============================================================================="
      cat /proc/1/cgroup
      echo "==============================================================================="
      cat /etc/*release*
      echo "==============================================================================="
      pwd
      echo "==============================================================================="
      df -kh .
      echo "==============================================================================="
      ls -al
      echo "==============================================================================="
      id
      echo "==============================================================================="
  - bash: |
      set -x
      git clone https://github.com/itemko/jenkins_scripts.git
      cd jenkins_scripts && git checkout artemry/ompi_review && cd - > /dev/null
      pwd
      ls -al
      export WORKSPACE=${BUILD_SOURCESDIRECTORY}/ompi
      ${BUILD_SOURCESDIRECTORY}/jenkins_scripts/jenkins/ompi/ompi_jenkins.sh
