# https://aka.ms/yaml

trigger:
  - master
# TODO all the PRs
pr:
  - master

pool:
#  vmImage: 'ubuntu-16.04'
  name: Default
  demands: CUSTOM_CAPABILITY -equals qqq

#container: centos:7

resources:
  repositories:
    - repository: jenkins_scripts
      type: github
      endpoint: itemko
      name: itemko/jenkins_scripts
      ref: artemry/ompi_review

steps:
  - checkout: self
    submodules: true
  - checkout: jenkins_scripts
  - bash: |
      echo "==============================================================================="
      hostname
      echo "==============================================================================="
      printenv
      echo "==============================================================================="
      cat /proc/1/cgroup
      echo "==============================================================================="
      cat /etc/*release*
      echo "==============================================================================="
      pwd
      echo "==============================================================================="
      df -kh .
      echo "==============================================================================="
      ls -al
      echo "==============================================================================="
      id
      echo "===============================================================================
  - bash: |
      export WORKSPACE=${BUILD_SOURCESDIRECTORY}/ompi
      ${BUILD_SOURCESDIRECTORY}/jenkins_scripts/jenkins/ompi/ompi_jenkins.sh
