# https://aka.ms/yaml

trigger:
  - master
pr:
  - master

pool:
  vmImage: 'ubuntu-16.04'

container: centos:7

steps:
  - checkout: self
  - checkout: github://mellanox-hpc/jenkins_scripts
    path: jenkins_scripts
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  - bash: |
      set -eE
      echo "==============================================================================="
      hostname
      echo "==============================================================================="
      printenv
      echo "==============================================================================="
      cat /proc/1/cgroup
      echo "==============================================================================="
      cat /etc/*release*
      echo "==============================================================================="
      pwd
      echo "==============================================================================="
      df -kh .
      echo "==============================================================================="
      ls -al
      echo "==============================================================================="
      id
      echo "==============================================================================="
