# https://aka.ms/yaml

trigger:
  - master
# TODO all the PRs
pr:
  - master

pool:
  name: Default
  demands: CUSTOM_CAPABILITY -equals ompi

container: centos:7

variables:
  ompi_jenkins_scripts_git_repo_url: https://github.com/itemko/jenkins_scripts.git
  ompi_jenkins_scripts_git_branch: artemry/ompi_review

steps:
  - checkout: self
    submodules: true
    path: ompi
  - bash: |
      set -eE
      echo "==============================================================================="
      hostname
      echo "==============================================================================="
      printenv
      echo "==============================================================================="
      cat /proc/1/cgroup
      echo "==============================================================================="
      cat /etc/*release*
      echo "==============================================================================="
      pwd
      echo "==============================================================================="
      df -kh .
      echo "==============================================================================="
      ls -al
      echo "==============================================================================="
      id
      echo "==============================================================================="
  - bash: |
      set -eEx
      sudo yum install -y git
  - bash: |
      set -eEx
      git clone $(ompi_jenkins_scripts_git_repo_url)
      cd jenkins_scripts && git checkout $(ompi_jenkins_scripts_git_branch) && cd - > /dev/null
      pwd
      ls -al
      export WORKSPACE=${BUILD_SOURCESDIRECTORY}/ompi
      ${BUILD_SOURCESDIRECTORY}/jenkins_scripts/jenkins/ompi/ompi_jenkins.sh
